name: open_camera_flutter_example
description: Demonstrates how to use the open_camera_flutter plugin.

publish_to: 'none'

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^10.4.3

  open_camera_flutter:
    path: ../
  cupertino_icons: ^1.0.2

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true



